services:
  llamaindex:
    container_name: llamaindex
    env_file:
      - .env
    environment:
      - ENV=$COMPOSE_PROFILES
    ports:
      - "8000:8000"
    build: ./
    restart: always
    volumes:
      - $PWD/storage:/storage
      - $PWD/rag_data:/rag_data

  tgi:
    profiles: [ "local" ]
    container_name: tgi
    image: ghcr.io/huggingface/text-generation-inference:1.4
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: always
    volumes:
      - $PWD/data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
